# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0007_uniquesetting'),
        ('push_notifications', '0010_alter_device_id_from_uuid_to_text'),
    ]

    operations = [
    ]
