# Generated by Django 4.2.11 on 2024-06-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0012_auto_20221031_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcmdevice',
            options={'verbose_name': 'FCM device'},
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='cloud_message_type',
            field=models.CharField(choices=[('FCM', 'Firebase Cloud Message'), ('GCM', 'Google Cloud Message')], default='FCM', help_text='You should choose FCM, GCM is deprecated', max_length=3, verbose_name='Cloud Message Type'),
        ),
    ]
